#!/bin/bash

echo "Setting up ClickHouse migration table"
docker compose up -d clickhouse

sleep 5

docker compose exec clickhouse clickhouse-client --query "CREATE DATABASE IF NOT EXISTS posthog ON CLUSTER posthog;"

sleep 3

docker compose exec clickhouse clickhouse-client --query "CREATE TABLE IF NOT EXISTS posthog.infi_clickhouse_orm_migrations_distributed ON CLUSTER 'posthog' (\
    package_name String,\
    module_name String,\
    applied Date DEFAULT '1970-01-01'\
) ENGINE = ReplicatedMergeTree('/clickhouse/prod/tables/{shard}/{database}/{table}', '{replica}')\
PARTITION BY toYYYYMM(applied)\
ORDER BY (package_name, module_name)\
SETTINGS index_granularity = 8192;"

sleep 3

docker compose exec clickhouse clickhouse-client --query "CREATE TABLE IF NOT EXISTS posthog.infi_clickhouse_orm_migrations (\
    package_name String,\
    module_name String,\
    applied Date DEFAULT '1970-01-01'\
) ENGINE = ReplicatedMergeTree('/clickhouse/prod/tables/{shard}/{database}/{table}', '{replica}')\
PARTITION BY toYYYYMM(applied)\
ORDER BY (package_name, module_name)\
SETTINGS index_granularity = 8192;"

echo
echo "✅ ClickHouse migration tables created"
