#!/bin/bash

echo "--------------------------------------------"
echo "SKIP_ASYNC_MIGRATIONS_SETUP: $SKIP_ASYNC_MIGRATIONS_SETUP"
echo "POSTHOG_SKIP_MIGRATION_CHECKS: $POSTHOG_SKIP_MIGRATION_CHECKS"

/compose/wait
/compose/idle

#./bin/migrate
#./bin/docker-server
